#!/bin/zsh

output_old=''

while true
do
    if [[ $(cat $neowatch_page_number_file_path) > -1 ]]
    then
        (( lines_from_top_num = (( $(tput lines) - 1 )) * $(cat $neowatch_page_number_file_path) ))
    fi

    # printf "[%s] Output of %s:\n" "$(date)" "$*"
    # "$@" <- we don't want to do it this way, just this:
    output_new=$(${SHELL-/bin/sh} -c "stty cols 120 && $*" | head -n $lines_from_top_num)
        if [[ $output_new != $output_old ]]
        then
            clear
            echo $output_new
            output_old=$output_new
        fi

sleep 0.1  # genuine Quartz movement
 
done

