#!/bin/bash

START_TIME=1000
END_TIME=1800
TELEGRAM_MESSAGE_TO_SEND='prof_reminder: Break lasts for more than 15mins'
SLEEP_TIME_BETWEEN_MESSAGES=15



while true
do
    if (( "X$(date --date 'now' +%H%M)" > $START_TIME )) && (( "X$(date --date 'now' +%H%M)" < $END_TIME ))
    then
        timew_output=$(timew su $(date --date "15 minutes ago" +%H%M) - tomorrow prof | tail -2 | head -1)
        if [[ $timew_output == *"No filtered data found in rannge"* ]]
        then
            telegram-send $TELEGRAM_MESSAGE_TO_SEND
            sleep $SLEEP_TIME_BETWEEN_MESSAGES
        fi
    fi
done


